'use strict'

require('./lib')()

/*
# REQUIRED OPTIONS
APP_ID
COUCH_URL
COUCH_USER
COUCH_PASS

# REQUIRED TWITTER OPTIONS
TWITTER_CONSUMER_KEY
TWITTER_CONSUMER_SECRET
TWITTER_ACCESS_TOKEN
TWITTER_ACCESS_TOKEN_SECRET
# OPTIONAL TWITTER OPTIONS
TWITTER_USER_ID

# REQUIRED INSTAGRAM OPTIONS
INSTAGRAM_ACCESS_TOKEN
# OPTIONAL INSTAGRAM OPTIONS
INSTAGRAM_USER_ID

# REQUIRED PODCAST OPTIONS
PODCAST_URL

# REQUIRED BLOG OPTIONS
BLOG_URL

# REQUIRED FACEBOOK OPTIONS
FACEBOOK_CLIENT_ID
FACEBOOK_CLIENT_SECRET
FACEBOOK_USER_ID

# REQUIRED YOUTUBE OPTIONS
YOUTUBE_NAME
YOUTUBE_KEY
*/
